if &compatible
  set nocompatible
endif

set runtimepath+=/Users/takapy/.vim/repos/github.com/Shougo/dein.vim

call dein#begin('/Users/takapy/.vim/')

" Let dein manage dein
" Required:
call dein#add('Shougo/dein.vim')

" Add or remove your plugins here:
"call dein#add('Shougo/neosnippet.vim')
"call dein#add('Shougo/neosnippet-snippets')
call dein#add('Yggdroot/indentLine') " :IndentLinesToggle toggles lines on and off.
call dein#add('tpope/vim-endwise')   " Automate end like keyword typing
"call dein#add('Townk/vim-autoclose')  " Close ' ) like symbol
call dein#add('osyo-manga/vim-monster') " Rubyの補完プラグイン
call dein#add('todesking/ruby_hl_lvar.vim') " Highlight local variable in ruby
call dein#add('airblade/vim-gitgutter') " Shows git diffs
call dein#add('itchyny/lightline.vim') " Light and configurable statusline/tabline for Vim
call dein#add('bronson/vim-trailing-whitespace') " Trailing whitesspace detected by red color
"call dein#add('tomtom/tcomment_vim') " Comment out efficiantly
"call dein#add('othree/html5.vim')
"call dein#add('hail2u/vim-css3-syntax')
"call dein#add('hokaccha/vim-html5validator')
"call dein#add('AtsushiM/sass-compile.vim')
"call dein#add('kchmck/vim-coffee-script')
"call dein#add('itmammoth/doorboy.vim') " Auto closing of blackets
"call dein#add('digitaltoad/vim-pug')
"call dein#add('vim-scripts/jQuery')
"call dein#add('Shougo/neocomplete')  "コード補完機能
call dein#add('pangloss/vim-javascript')  "vim-jsx depends on this
call dein#add('mxw/vim-jsx')  "hilighting and indent support for jsx code
"call dein#add('keith/swift.vim') "sintax highlight of swift code
"call dein#add('Shougo/unite.vim') "filer
"call dein#add('Shougo/vimfiler.vim') "uniteを全体にしたfiler
call dein#add('scrooloose/nerdtree') "ディレクトリ表示
call dein#add('udalov/kotlin-vim') "Kotlinのシンタックスハイライト
call dein#add('rust-lang/rust.vim') "Rustのシンタックスハイライト
call dein#add('cohama/lexima.vim') "クオーテーション補完

" You can specify revision/branch/tag.
call dein#add('Shougo/vimshell', { 'rev': '3787e5' })

" Required:
call dein#end()

" Required:
filetype plugin indent on

" Configure NERDTree
let NERDTreeShowHidden=1

" Configure aliases here
:command Nt NERDTree
:command Tind IndentLinesToggle

" If you want to install not installed plugins on startup.
"if dein#check_install()
"  call dein#install()
"endif

:syntax on

set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set autoindent
set autoread
set smartindent
set number
set hlsearch
set mouse=a
set backspace=2
set encoding=utf8
set hlsearch
set incsearch
set wrapscan
set noswapfile
set ruler
set showmatch
set title
set laststatus=2
set clipboard=unnamed,autoselect
set encoding=utf-8

colorscheme molokai


" Fortran!!!!!!!

" Ensure correct syntax highlighting and auto-indentation for Fortran free-form
" source code.
let fortran_free_source=1
let fortran_do_enddo=1
filetype plugin indent on
syntax on

" Turn on line numbers and row/column numbers.
set nu
set ruler

" Make vim echo commands as they are being entered.
set showcmd

" Set tabstops to two spaces and ensure tab characters are expanded into
" spaces.
set smarttab
set expandtab
set smartindent
set autoindent
set tabstop=2
set shiftwidth=2

" Fix backspace key.
set bs=2

" Set up searching so that it jumps to matches as the word is being entered and
" is case-insensitive.
set incsearch
set ignorecase
set smartcase

" Uncomment the following lines to make
" vim automatically create a backup copy
" each time a file is edited.
"
" If you enable this feature, be sure to
"
"   mkdir ~/codeBackups
"
" or it won't work.
"set backupdir=~/codeBackups
"set backup

" Fortran end!!!!!!!!!
