- set_fact:
    python: {}

- name: check pyenv
  command: |
    bash -lc 'which pyenv'
  register: which_pyenv
  ignore_errors: yes
  changed_when: False

- name: install pyenv
  command: |
    bash -lc 'anyenv install pyenv'
  when: which_pyenv.rc > 0

- name: get installed versions
  command: |
    bash -lc 'pyenv versions'
  register: installed_versions
  changed_when: False

- name: install python
  command: |
    bash -lc 'pyenv install {{ item | quote }}'
  when: |
    installed_versions.stdout.find(item) == -1
  with_items: '{{ python.versions }}'

- name: set global python
  command: |
    bash -lc 'pyenv global {{ python.versions[0] | quote }}'
  changed_when: False # TODO: Need valid condition

- name: rehash
  shell: |
    if [ -f "$DOTSHIM_FILE" ]; then
      rm -f "$DOTSHIM_FILE"
    fi
    bash -lc 'pyenv rehash'
  environment:
    DOTSHIM_FILE: '{{ anyenv.envs_dir }}/pyenv/.pyenv-shim'
  changed_when: False # TODO: Need valid condition
